apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketdex-deployment
  labels:
    app: rocketdex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rocketdex
  template:
    metadata:
      labels:
        app: rocketdex
    spec:
      imagePullSecrets:
      - name: ghcr-secret # Reference to the secret for the private registry
      containers:
      - name: rocketdex
        image: ghcr.io/ykhadnevich/ykhadnevich-gh-actions-workshop:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
