name: Hello World Training Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened, edited] # Trigger workflow on issue creation and editing

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      MY_ENV: "John Doe" # Setting a job-level environment variable

    steps:
      - name: Greet the User
        run: echo "Hello World!"
      
      - run: ls -l

      - uses: actions/checkout@v2

      - run: ls -l  

      - name: Run a multi-line script
        run: |
          echo "Hello $MY_ENV"       # Access the custom environment variable
          echo "Hello $GITHUB_ACTOR" # Access the default GitHub-provided environment variable
