apiVersion: v1
kind: Service
metadata:
  name: rocketdex-service
  labels:
    app: rocketdex
spec:
  type: NodePort # Expose the service externally
  selector:
    app: rocketdex
  ports:
  - port: 3000 # Internal application port
    targetPort: 3000 # Matches the containerPort in the deployment
    nodePort: 30001 # Exposes the service on this port

